framework:
    notifier:
        channel_policy:
            urgent: ['browser']
            high: ['browser']
            medium: ['browser']
            low: ['browser']

        admin_recipients:
            - { email: admin@example.com }
