<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLuQX37f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLuQX37f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLuQX37f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLuQX37f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLuQX37f\App_KernelDevDebugContainer([
    'container.build_hash' => 'LuQX37f',
    'container.build_id' => '7de938f5',
    'container.build_time' => 1713245186,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLuQX37f');
