#index:
#    path: /
#    controller: App\Controller\DefaultController::index
modifier_utilisateur:
  path: '/utilisateur/modifier/{id}'
  controller: 'App\Controller\UtilisateursController::modifier'
  methods: ['GET', 'POST']

app_utilisateurs_display:
  path: '/utilisateur/{id}'
  controller: 'App\Controller\UtilisateursController::display'
  methods: ['GET']

app_front:
  path: '/'
  controller: 'App\Controller\UtilisateursController::index'
  methods: ['GET']
  
app_back:
  path: '/back'
  controller: 'App\Controller\UtilisateursController::index1'
  methods: ['GET']

app_login:
  path: '/login'
  controller: 'App\Controller\SecurityController::login'
