<?php

namespace ContainerLuQX37f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5Q5aQHCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Q5aQHC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Q5aQHC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'materiaux' => ['privates', '.errored..service_locator.5Q5aQHC.App\\Entity\\Materiaux', NULL, 'Cannot autowire service ".service_locator.5Q5aQHC": it references class "App\\Entity\\Materiaux" but no such service exists.'],
        ], [
            'materiaux' => 'App\\Entity\\Materiaux',
        ]);
    }
}
