<?php

namespace ContainerLuQX37f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5Pa_G1hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5Pa.g1h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Pa.g1h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cosplayRepository' => ['privates', 'App\\Repository\\CosplayRepository', 'getCosplayRepositoryService', true],
        ], [
            'cosplayRepository' => 'App\\Repository\\CosplayRepository',
        ]);
    }
}
