<?php

namespace ContainerLuQX37f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SZ5a98Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sZ5a9_8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sZ5a9_8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CosplayController::delete' => ['privates', '.service_locator.zuat7N1', 'get_ServiceLocator_Zuat7N1Service', true],
            'App\\Controller\\CosplayController::edit' => ['privates', '.service_locator.zuat7N1', 'get_ServiceLocator_Zuat7N1Service', true],
            'App\\Controller\\CosplayController::index' => ['privates', '.service_locator.5Pa.g1h', 'get_ServiceLocator_5Pa_G1hService', true],
            'App\\Controller\\CosplayController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\CosplayController::show' => ['privates', '.service_locator.dL1IMo4', 'get_ServiceLocator_DL1IMo4Service', true],
            'App\\Controller\\MateriauxController::delete' => ['privates', '.service_locator.Eqcy1JR', 'get_ServiceLocator_Eqcy1JRService', true],
            'App\\Controller\\MateriauxController::edit' => ['privates', '.service_locator.Eqcy1JR', 'get_ServiceLocator_Eqcy1JRService', true],
            'App\\Controller\\MateriauxController::index' => ['privates', '.service_locator.jYOkK4L', 'get_ServiceLocator_JYOkK4LService', true],
            'App\\Controller\\MateriauxController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\MateriauxController::show' => ['privates', '.service_locator.5Q5aQHC', 'get_ServiceLocator_5Q5aQHCService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\CosplayController:delete' => ['privates', '.service_locator.zuat7N1', 'get_ServiceLocator_Zuat7N1Service', true],
            'App\\Controller\\CosplayController:edit' => ['privates', '.service_locator.zuat7N1', 'get_ServiceLocator_Zuat7N1Service', true],
            'App\\Controller\\CosplayController:index' => ['privates', '.service_locator.5Pa.g1h', 'get_ServiceLocator_5Pa_G1hService', true],
            'App\\Controller\\CosplayController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\CosplayController:show' => ['privates', '.service_locator.dL1IMo4', 'get_ServiceLocator_DL1IMo4Service', true],
            'App\\Controller\\MateriauxController:delete' => ['privates', '.service_locator.Eqcy1JR', 'get_ServiceLocator_Eqcy1JRService', true],
            'App\\Controller\\MateriauxController:edit' => ['privates', '.service_locator.Eqcy1JR', 'get_ServiceLocator_Eqcy1JRService', true],
            'App\\Controller\\MateriauxController:index' => ['privates', '.service_locator.jYOkK4L', 'get_ServiceLocator_JYOkK4LService', true],
            'App\\Controller\\MateriauxController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\MateriauxController:show' => ['privates', '.service_locator.5Q5aQHC', 'get_ServiceLocator_5Q5aQHCService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\CosplayController::delete' => '?',
            'App\\Controller\\CosplayController::edit' => '?',
            'App\\Controller\\CosplayController::index' => '?',
            'App\\Controller\\CosplayController::new' => '?',
            'App\\Controller\\CosplayController::show' => '?',
            'App\\Controller\\MateriauxController::delete' => '?',
            'App\\Controller\\MateriauxController::edit' => '?',
            'App\\Controller\\MateriauxController::index' => '?',
            'App\\Controller\\MateriauxController::new' => '?',
            'App\\Controller\\MateriauxController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CosplayController:delete' => '?',
            'App\\Controller\\CosplayController:edit' => '?',
            'App\\Controller\\CosplayController:index' => '?',
            'App\\Controller\\CosplayController:new' => '?',
            'App\\Controller\\CosplayController:show' => '?',
            'App\\Controller\\MateriauxController:delete' => '?',
            'App\\Controller\\MateriauxController:edit' => '?',
            'App\\Controller\\MateriauxController:index' => '?',
            'App\\Controller\\MateriauxController:new' => '?',
            'App\\Controller\\MateriauxController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
