<?php

namespace ContainerLuQX37f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Eqcy1JRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Eqcy1JR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Eqcy1JR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'materiaux' => ['privates', '.errored..service_locator.Eqcy1JR.App\\Entity\\Materiaux', NULL, 'Cannot autowire service ".service_locator.Eqcy1JR": it references class "App\\Entity\\Materiaux" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'materiaux' => 'App\\Entity\\Materiaux',
        ]);
    }
}
