<?php

namespace ContainerLuQX37f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCosplayService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dL1IMo4.App\Entity\Cosplay' shared service.
     *
     * @return \App\Entity\Cosplay
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.dL1IMo4": it references class "App\\Entity\\Cosplay" but no such service exists.');
    }
}
