<?php

namespace ContainerLuQX37f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMateriaux2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Eqcy1JR.App\Entity\Materiaux' shared service.
     *
     * @return \App\Entity\Materiaux
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Eqcy1JR": it references class "App\\Entity\\Materiaux" but no such service exists.');
    }
}
